language: java
dist: trusty

env:
  global:
  - secure: "kKg1KjouuOvDBIMpvmzAVjYZpyVEiAfghPq36gVQbxUR6UYP6ynHzZMxs4SYBTs+jd/Lm8CdteL6x4xI4KumMlxBhcWTobdqc5DYyc3FxjHNtatrd9BleOnnlZb0r1o6KDlo+kfqYZPjJvALaAyRJBQGF+UFlBIK9IouHXP6IVOGMN51p67L1Lny3a+zRITNI/0qqqClL8etybQW+Fl0TiKlFBUp0QyxOpHnghBqHxc/YCBwDSET2tZ/tmtnvgSpUiCAUgV9PDkah48mSgRyHmdsL+04T+lKhvSVkR0oyx8hNAnKIS+PCv3YrLnjg8uAF3uiMK1dM+qhCF1yIxRFzGfrzBbMF7CmNYeo4vQXQriQSoBFi9wm2yrBYnRRjyGlfQg8VhAsPFlaeyb/1ELdLbUL1EMHYJoRdmhBsPppxlbcKXa3g3FIX2nYhraqTr3Qys3Df3YLraLMgUC04V1liOKBoWlGbup0CJ+BFLIlfF/SlXkRTpPZ2Hk9Jw3OEePgrqHXlSHjG7r9YU96l8wkx/cKVjC+dgpFy3UShu6vSps7SepT9Aqn3Gn3hgLzufMuJGmJErduQ40LqDqeZaiBfos2zsUn9kkA6kuK+50FmPgc2LPVmfgs28zXjWxchITNJS3nxBtolZMpkFnp+o7icZc4mQwq5s5tO3GmSRSv0rY="
  - secure: "CNhAoGXbz+ppNVfkIO1AsTuZKXxXuYp07C+kQUBdfIrENorHPpL0o41w6FezVrdZku6rYJ/LlJpidkvD3A6avfAFvYZHg8GMszMuEwRwQU++d9JvViVo+l2YctVPZ7QCGSbX7hRjo4ciLGh16POrqYk7cwgF9usQzU8rj0lT6/AziEmpX473VmcO5WXlJE2AYcl1tCRDdlGLhRK+Sj6NmynEnMJROphj0Pb+x/1jXn8aS5XeaF2KWeojVEOHldjKkxYI4CkBzQViHdB+xaA84Ro+9KHUAMpbmc6XHQXvRW6gBHTOsbjACQhQwmaflvUSGbjywEniKHBuim4zk74pU/TZfxn6ZcuTgMXXflL9HHI02aGO8LCzDbMUielrxRuNJrqEhMQsvt+EmcQFKJiAucy7jaYjAR97CK/KmsCgUC1gKcT7QkHEpkBz4D7J/sVyD5Q8PZvXSW+1PQIiIiPseMIQheQHrMSXVCIGGmlhr/vJ9ytIjOQLXt9VeB9hZ6LVPW1Ct4MheJJz8ny9nX5oFSa/IJBFL5Tk2yWW4ifQMo4umlLLyRTyaPvIdpS3Z6zO+/f3y/6pHvTqxqwM2pB5eoezeMonW5k+/S7E+ufgVHXHnKHK3koq3Qkdwqbf70rCuH5S9jFGikEIIw/EfKhQGxRpNFWxoVOQIBsQr9SN+ns="
  - secure: "p2dFmtvU1yKjQ2aaiXqV9FXC3Xz/AYPrNnz/S08wiUY/M0M7z9bvR2rmOoQr9cg+9ztE/WOnTCq8cJRnfv/q58x7wS2KgcPryV2BK81CNwhIZWf9FSx0UjK7NiZ4Xsf0+4Kw0t7nVpuzc3JUWOivEk1em9ZgSgBr7+gm5VylHdxTM5uXvgOlInfubJvB3+YGT9yKCSqAIqVfQr4c/Sda4S/hql6/iNK+H4noVoEBU4xMx+XiBxuOpZom+C9XYLk+eKEI3tTAw/Dvf6syGrLF+kwqcD/gqQT2eDFl4iKX3ZpQz/C9XpineICfD41bg0bAl+g6KElIpO9gD8uuCf/KNdpx4lkjyzgj4DBBwRdey+aO98PywUTc1sZ+A0L7k3KQlQDvj0fUTdSNOX6bsiyqSPa2y71YlhJB+74neKo9xhrqd3PforRcK6zqLILSIwidLOv5o/gxWEXsQym9BeVCRqUPOwKsIxR3du6eqSjPJ9U9adphh5bxGBljpnpRWMj91r0L3AtUXtTG8Vjv+sOAcl3jprqBp1UukwV/Y6u/qPUMMF4tWvI3/ZZrEN4Socu4OUf52xYO/L7beSfpwPuUTjLyPS03NDrFLei3bC3Lp64knUoQ0LEfeeKYcf0HoW5cUPWBlGAhjzWhxcDfBG3uqInNFLsxfRHTR9p42B5SgEM="

jdk:
- openjdk8

cache:
  directories:
  - $HOME/.m2

before_install:
- openssl aes-256-cbc -K $encrypted_f32d9b726118_key -iv $encrypted_f32d9b726118_iv
  -in gpg.tar.gz.enc -out gpg.tar.gz -d
- tar zxvf gpg.tar.gz

install: mvn clean install -DskipTests=true -V -U

script: mvn test

after_success:
- mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml
