language: java
dist: trusty

env:
  global:
  - secure: ovPzRWGHWD+QmnCrXPXW/EW1XhUQyRY4IvUk4QNVIgjQ9hs29HxLy5yHgmdyKS7NQIuLOsbM+4KwvkskmAnIQbYwBVOTEQpOUT9gncCNifXPhiti4r9XotyiSzqqDCBi0bn6UR3XA3Djid7XTf0tmfDJF5cv2cZf5y/5ZJgH0DjzQC7qfOq2wflKb8wiqPWbZIys8XYpgYkWpIQ/z36qnZaTaEPSSMJBMvow0Bi8bOzhpHr+u/LmT+wEj2cCb4UhEImm4t3QaswZVRG3Ko9l4U8vo2Ps7IdYzMYRxEE9TUmjCfUy/dxPGBl3Bk+POPoveghkNz/DImqZ+v1oAjvgFzo3MuRboKHAMYvv1zb6qr+jDjL0gI+3glLOBri18tTQxKqj3oUCRE2iJ698l95FYtxKth/Jeaq2jwDhDPuNKByMGuwIGBvL3m/Xah1hJb21eX+Al0ocC6/+5l6Jhgi0aDqyTPyuWzDtwwwoeCgl/u+FLE02lZCxIIm1sLItX9KA3FQYmP0yTPD8JgCDEBwfP2szYcW2HJV3AA02FV0IffR2Oks8ELzL/hjnihnPmFvEucenV8SJs7hPnx0dC/piHb2XXdNbNMgC2tKFBjk2SRB4bgUWDmFY8HIHoTsvghE2NJW2NP5u11JXLwSpO3ca6nYNCJmPogd18TqKSVncyrw=
  - secure: X7DLXhYe8JdqSoKoNQm8QOZv/GdjjzilqeeG5Hikdefs9aHlLOLxEA2SnXZmtvNYlN3xAcRUi3w+KGzi/XSBQyLmZ2Te7VEVMn9tGYEMOtwXyY8U008w9ukb2OSYXezOxyx1LKJMtMgYg2IActEk0C8yX17H8HB332Rrdg2LUBQThwsj3vMxj1GOCyeYPoD84dklBQ9M66YJ+6ShsyQ+bgmQKfioudGa5QMYS/iDYVFRRFhDMScT5dL7/zb3MQbJeTjieu7/6sD0gdlefIkI3EWRUrHh69Nrx80hQ/zZwpKJWqLoQKSRzo1WIoPoY4TVx1jVWKS7IpTk1MTPN2Un/wWTtftyKic4wtLAhNAnaChfn5ici99guDJeIpGmNAe/6cD2tEW4xt06LcmE0Ew8qtHxcUvxq0nEUx+FaYpK9f4mIiq8Bes+xHesotD8TbT9nr2XoEMWWoCiQLvzw/oVavmipS13p6tOE8py/OZCrX/KunaNNcp8odtRAhnmsnpk5X9Fxt8+bqrNZUPI6FaRPOQdHtAiiXDge2TpaW2YDN9uhPv8z5VOaE4YHL27KJiqWshzBGaizU/om9gfmJTOohG9UQ5w+J4MAHgx71Db/9bbBJNC7+4UnicBm7xze1ICYeILMk/fQvpQBBdrqYzQ1At7gzSOV0ONDrS/A7Apt6E=
  - secure: nTY/NfKoUU0l+72pYkG7dAvhtBNSZ6DdKUoe4lLDzBsenEpIic1SAueUpA9zi6Plf0lQrqAjKcRu9k26lPF6Kj52LpyvnAS1o+rOhPOHFzi69hPAYHVfbH4Zyjm0B9BSrpAqULrjNm20nGCAzTKVZWVNZgTJ/DVbO4qpN40XZulzLoQWq+sIk9cbpcF00hw11AyP9DLyKx0OLisxcQXH0ytDu3DUxe8RUbWF7iOTJzwB+p2TLknUUZfTzGn7MmI2gb2G1LTQpa65r+svHgmpUjLE2QqSAxL8jumXmpHsUwKRZijMa/wc9HD7PHlroPaOi8Tm3nyCy/L7lZL5xIHSakce4t0hNRdvAWsu6FcPRtTo3jsYp0fhECudVZqwb78mHjSEhWSSc8GC2RPGA0P2K75EMJ2Tp4Z0JmA4s+gPRm2aB8juxSZIezmUGMAcakauDsxENTINjaoGiROgLyc9o7bvG2An3DVymiK1vt2DQHhHKQjsH4v0dMQ+W+OMRn3CiEUAuI1aq28KUCtATcjNlfzngvJeTxs+FvYwv3sP0tpBF5maCsvbKrbPh5yjNiBNHBiqeVzXZD72wLM+TPu1ngOkecBqa8pWQP654hTnvmDs/3wk0NOOCm7kDFzNvDH0QiChx3zDlSq6gUcpLTSyAB/2Rl1ufxFB4noEw/Kfh34=

jdk:
- openjdk8

before_install:
- openssl aes-256-cbc -K $encrypted_f32d9b726118_key -iv $encrypted_f32d9b726118_iv
  -in gpg.tar.gz.enc -out gpg.tar.gz -d
- tar zxvf gpg.tar.gz

install: mvn clean install -DskipTests=true -V

script: mvn test

after_success:
- mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml